---
title: "9. Box Jenkins Models for Stationary, Non-Seasonal Time Series"  
output: 
  html_document:
    toc: true
    fig_caption: true
bibliography: bibliography.bib      
---

# A. Some Simple Box-Jenkins Models and Their Properties

## i. ARMA(0,0)

## ii. MA(1)

## iii. AR(1)

## iv. ARMA(1,1)

## v. General Notation

The Box-Jenkins ARMA(p,q) model is denotedby the equation

$$ y_t = \phi_0 + \phi_1 y_{t-1} + \phi_1 y_{t-1} + \cdots + + \theta_1 a_{t-1}  + \theta_1 a_{t-1}  + \theta_1 a_{t-1}  $$

The white noise error terms $a_t$ are assumed to have the following properties:

1. $\mathbb{E}(a_t)=0, \quad \forall t$ (zero mean assumption)
2. $\mathbb{E}(a_t^2)=\sigma_a^2, \quad \forall t$ (constant variance assumption)
3. $\mathbb{E}(a_s a_t), \quad \forall t\neq s$ (independence of errors assumption)
4. $a_t$ are normally distributed

## vi. Concepts of Stationarity and Invertibility

<!-- see BJ notation -->


# B. Identification Tools

## i. Autocorrelation Function (ACF)

## ii. Partial Autocorrelation Function (PACF)

# C. Pattern Table

Model   ACF        PAFC 
====== ========== ===========
AR(q)  Tails off  Cuts off

# D. Sample Counterparts

# E. Information Criteria

# F. P/Q Box

# G. Overfitting Exercises

# H. Example: Lead Production Data

# References
