---
title: "15. Combining Forecasts"  
output: 
  html_document:
    toc: true
    fig_caption: true
bibliography: bibliography.bib      
---

*  @diebold:2007 Chapter 13

# A. Combination Forecasting

Reading @diebold:2007 Chapter 13

* Let us consider the statistical properties of the combination forecast

$$ \hat{y}_{t}^{(c)}=\hat{w}_{t}^{(1)}+(1-\hat{w})f_{t}^{(2)}$$


## i. Some Basic Theorems of Diversification of Forecasts

* __Theorem 1: (combination of unbiased forecasts unbiased)__

* __Theorem 2: (variance of combined forecasts)__

* __Theorem 3: (optimal forecasts weights)__

* __Theorem 4: (diversification pays)__


## ii. Nelson Combination Method

__Assumption:__

* Both methods produce unbiased forecasts. That is

$$\mathbb{E}(e_{t}^{(1)}) =  \mathbb{E}(e_{t}^{(2)}) = 0 $$

The estimation equation for deriging the __Nelson combination (ensemble) weights__ is 

$$ \hat{y}_{t}^{(N)}=\hat{w}_{t}^{(1)}+(1-\hat{w})f_{t}^{(2)}$$
or equivalently, 

$$ \hat{y}_{t}^{(N)}=\hat{w}_{t}^{(1)}+(1-\hat{w})f_{t}^{(2)}$$


## iii. Granger-Ramanathan Combination Method

__Assumption:__

* One or more methods produce biased forecasts. That is, for at least one fot the methdos,


$$\mathbb{E}(e_{t}^{(i)})\neq 0 $$
The estimating equation for deriving the __Granger-Ramanathan combination (ensemble) weights__ are

$$ \hat{y}_{t}^{(GR)}=\hat{w}_{0}+\hat{w}_{1}^{(1)}+\hat{w}_w f_{t}^{(2)} + \varepsilon_t$$

$$ \hat{y}_{t}^{(GR)}=\hat{w}_{0}+\hat{w}_{2}^{(1)}+\hat{w}_2 f_{t}^{(2)}$$


## iv. Combinations with Time-Varying Weights


# B. Application to Economic Time Series

```{r}
x<-1:100
plot(x)

```

# References